"""Initial migration

Revision ID: f979c544eeac
Revises: 
Create Date: 2026-07-23 03:37:49.407189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f979c544eeac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agri_info',
    sa.Column('info_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('info_id')
    )
    op.create_table('crop',
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('crop_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('diagnosis',
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=200), nullable=False),
    sa.Column('predicted_disease', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('diagnosis_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.crop_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('diagnosis_id')
    )
    op.create_table('disease',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('disease_name', sa.String(length=100), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('prevention', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.crop_id'], ),
    sa.PrimaryKeyConstraint('disease_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disease')
    op.drop_table('diagnosis')
    op.drop_table('user')
    op.drop_table('crop')
    op.drop_table('agri_info')
    # ### end Alembic commands ###
